language: python
python:
- '2.7'
install:
- sudo add-apt-repository -y ppa:texlive-backports/ppa
- sudo apt-get update
- sudo apt-get install texlive make
script:
- (cd sheets; LATEX_OPTS="-interaction=nonstopmode -shell-escape" make pdfrelease)
deploy:
  provider: s3
  access_key_id: AKIAJNGHJWMQEU6QAIPQ
  secret_access_key:
    secure: tviNwD7V1A4WRzCwnRGXTHUf6kdbEG+7X7AxnTnSEf+ar1iXl/1aplLKFccc9vwzlGy0sUVqv0wg0kmQkIMhUhdZovOD4gUnOARUZzkTHj9L0apIb2gxLyEyYHCRFiIKLT6Vto8iPbU3ALCoQAhk2oQwM+dznQb6lg+U5HpRK8U=
  bucket: livewires-worksheets
  local-dir: release
  upload-dir: "$TRAVIS_BUILD_NUMBER"
  acl: !ruby/string:HighLine::String public_read
  on:
    repo: livewires/python
