language: python
python:
- '2.7'
install:
- sudo apt-get -qq update
- sudo apt-get install -y -f texlive-full make
script:
- (cd sheets; LATEX_OPTS="-interaction=nonstopmode -shell-escape" make pdfrelease)
deploy:
  provider: s3
  access_key_id: AKIAIYRRK52DO5HPYNJA
  secret_access_key:
    secure: SNVeIbn6BvxiQhOC6AHwjw3JmgIE+0KYFaDcY8hAqcVnTreEj7dlnmap0bW+2pafC7cgWn6e1ruIo+W0cP74FCIvPKta1mzpuzUSYWv2uB1nIbTrIW2fAkhTklj1xgLXG61wJKJr5BWVlAGHHAtFp1rQzflxt0gxzsuwzzhUmHmXaaxZROZm7vip5Mi+azoMa1j56oHOfBS0sIq2CvyirPpUH1W8T99d8zEiYluw96WxIQAupvUWRM5Si5XmeoOmlbsSh1h75BIO1CUQYnCACyfCtyYRUJEKm4IBWXlS9B1Z+8W6BGsjxmE6qSsJReT3o4IWDarEf/31B5dyeOcle1JtjUFcXKorFkPZkb0G7EwxNbfQ3ONJkjRh9DDCiQflPjIupWa04GkghXzulSGoDcIThiHqYRSzutH5Zti+QXTzFPAU/YdhVJI9XBr+daMnTRpoxi0MBPVOtoEnyItdLwOefjwO80kgX+S3t3r1xFfiqKfJz3DW3WCkKuRZs1izLZADQk17MVVrW6UqMKRItzMT8NYXFhTT75GW8vsHn2z4idTa4CErWrBb1bSYQoOyZvm0/XHOca+s1jZgn0vt6stN/dyavZtFxTWO3deHEkUzB3ziJQEhvJNabxy60MzQMX2Updals6rdabAF4+WnrgBfdr3faISy9F96NIjrsIc=
  bucket: pieisreal-sheets
  local-dir: release
  upload-dir: "$TRAVIS_BUILD_NUMBER"
  acl: public_read
  region: ap-southeast-2
  skip_cleanup: true
  on:
    repo: CentricWebEstate/pieisreal
