language: python
python:
 - "2.7"
install:
 - "sudo add-apt-repository -y ppa:texlive-backports/ppa"
 - "sudo apt-get update"
 - "sudo apt-get install texlive make"
script:
 - cd sheets
 - LATEX_OPTS="-interaction=nonstopmode -shell-escape" make pdfrelease
