language: python
env:
 global:
  - "ARTIFACTS_AWS_REGION=eu-west-1"
  - "ARTIFACTS_S3_BUCKET=livewires-worksheets"
  - secure: "EmkksC2U3V+HU9OgIbuQ/E1RNCfQ/W/b250eXYYK8PT4NvDpzVn5NLatFmxI1ok90el6bmUbj6Bmk6p+JKic9Z4OM+fkEuZblCIbFHvBKC/U7Xy5wV+wEykWpyZd1wFS3iSt3AM4Ick2xxcRJ/qwb4L9Kt4cnJ7Xmq1WiBWKkzE="
  - secure: "xKZ6L4BxOg2wWMe71i/581nqNEeUO5oEtlXJlvzMJCKkwVbazuR3hTCK2hIPJFRX6SoCGAaXhtcBo8HGPizll226VUnhh9CPoyCm/zwI51nRtzWlsBbnTVvT/QfRLnVEKWE1miADKrqQXT0x+jTa1G3K2h656u7t8/cnkdtA6Xo="

python:
 - "2.7"
install:
 - "sudo add-apt-repository -y ppa:texlive-backports/ppa"
 - "sudo apt-get update"
 - "sudo apt-get install texlive make"
before_script:
 - "gem install travis-artifacts"
script:
 - (cd sheets; LATEX_OPTS="-interaction=nonstopmode -shell-escape" make pdfrelease)
after_script:
 - "travis-artifacts upload --path release/livewires-pdfs.tar.gz"
