language: python
python:
- '2.7.10'
install:
- sudo add-apt-repository -y ppa:texlive-backports/ppa
- sudo apt-get update
- sudo apt-get install texlive make
script:
- (cd sheets; LATEX_OPTS="-interaction=nonstopmode -shell-escape" make pdfrelease)
deploy:
  provider: s3
  access_key_id: AKIAJNGHJWMQEU6QAIPQ
  secret_access_key:
    secure: "dRilRvRvlob1nqKkcdphgO0dgIGEsTa+ol1TOmRJxtDaGHHJWW9d3uqd/O3+0wx9JAeZat8931FcjCvwZVBO6FIh+QKtVfwrXzkghxZR+OMc/ILk+1hColOrD2snh5l7mubkIdLHXRbp/LD37Qrua0hPzo70sCsslnNFoVZpIffk9FPCcnacNYxa2hMGx0D9OR8TMlXLLq+zdzTRQIWFPwhbUw03UPq9gqbZIYm6+qgER+wAnWLuapSF849tuK+PKNRs50bKV17xY0u8l9xpmr++JjNn7LvwlaJWSPWUbFpYRFJOf0Id7SBC5+5GX2f7VsEPe9K3x0Iik7R7aoui7xRdGJGjSMUOcKlpZt/x+BIy6I+oq6KG8cZ+kVZSyHrR/HSC2iyQ9mnJGZBLplic0gfv3akZJ5qoe22OBr9cZc4cpunFjewTKdHWSlzaZJ30qQ09pC2rvleqmsrmDFYfBoBA7Y9NDjJQ6nfTbW78t+P063DwoG57J5XfbBzFQE8hmmLhW2GWtZoi7+9MhClBL64UIjJCVOjtuBGn5uEfBGTDPY0jEh+ZTKZGiFaXLV1yDwwxAvvJFOZ0xTxIZTt156MmkmAhYu9mYaUa49DWL8OxxYslOkMoYB0LXpRe1EhQvL4ahzuv992AzpGD0QH7mVrYXJszDRW9pa7o0wxG524="
  bucket: pieisreal-sheets
  local-dir: release
  upload-dir: "$TRAVIS_BUILD_NUMBER"
  acl: public_read
  region: ap-southeast-2
  skip_cleanup: true
  on:
    repo: CentricWebEstate/pieisreal
