language: python
python:
- 2.7.10
install:
- sudo add-apt-repository -y ppa:texlive-backports/ppa
- sudo apt-get update
- sudo apt-get install texlive make
script:
- (cd sheets; LATEX_OPTS="-interaction=nonstopmode -shell-escape" make pdfrelease)
deploy:
  provider: s3
  access_key_id: AKIAJHWWUCZ75JOC2KKQ
  secret_access_key:
    secure: JVApbACOhcKu/Z1xy8jEnbxSDxx1o2anXvD7LgEJLSyhRf1N1ljJXwbsrkcAIFd6HNd3d0WSWoPkXkaz8qxSPzQcx7KXmNGuem9wlmndULcZSAtAuexMMOn43K6+glx9VCaiaBQk2c/hLAwGFrY7JJAJsh2/mS6caqCL+BIy1fKZXuD7nVWGtN93SO39tsBdgGR4YZXmv1Qa6GIIAqfLkJPGX9ILi9yNpmm8O1BHB62OQoLJ65Xt3aAfnuopxKaZbxoDTLK/KOKG7/6z/KaFfIeo9t+yeN1ASihEI9XoPSVXcbNzme53UxjpukSaQictfZ8Iujp9skiMnc1ttbARpe7FmijDCGCvoieCTTk+TdZu+XRg06xDqEEXvNKpQ35H8XVKXEqYmxtMGvFzaRWYo+FExQOvU/5JzQfuu0vXnDCXgaeZjIqdhkkrxndc0E7QdF2TleeIzKpYisFYofKaQKyKZV7KbnOOppNaAG56Lc7dXtkRBhQX1SKtbOSnq0C+I0ki5LsSdLWW8JMLLkarh1PMRtLsglcsY/XaiJUKUxk4tbkKkTCSsXpQfdV+gf2ohmYKqlOtGA9g64aq2G2ip6aW8GcsDDL4doqTiTa0Wuu+oteBdEjMLc2qOMoC0OUlHfnOukwpuQFtCUL4oM7u52xFSxrL6rHlQlGTsKUd2DA=
  bucket: pieisreal-sheets
  local-dir: release
  upload-dir: $TRAVIS_BUILD_NUMBER
  acl: public_read
  region: ap-southeast-2
  skip_cleanup: true
  on:
    repo: CentricWebEstate/pieisreal
